server:
  port: 5050
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydbprova
    username: root
    password: qwerty
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialize: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  mail:
    from: devtestdevtest828117@tiscali.it
    host: smtp.tiscali.it
    port: 465
    protocol: smtp
    username: devtestdevtest828117@tiscali.it
    password: _DkW3bwVqWVh3vG
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
mail:
  smtp:
    starttls:
      enable: false
debug: true

project:
  image: images/

authframework:
  jwt:
    hskey: KTlgvPcXbnLoYl6b5Ma1oG294dGoZ+fyxBqJiBjQjVo=
    audience: testaudience
    token-ttl: 86400000

